# Generated by Django 3.1.7 on 2021-03-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattribs',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='moblie_number',
        ),
        migrations.RemoveField(
            model_name='userattribs',
            name='phone_number',
        ),
    ]
