# Generated by Django 3.1.7 on 2021-04-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_userattribs_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribs',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
