# Generated by Django 3.1.6 on 2021-04-12 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20210409_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.TextField(blank=True)),
                ('Q2', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project_question'),
        ),
    ]
