# Generated by Django 3.2 on 2021-05-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribs',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userattribs',
            name='github',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userattribs',
            name='instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userattribs',
            name='twitter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
