# Generated by Django 3.2 on 2021-05-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_auto_20210501_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
