# Generated by Django 3.2 on 2021-05-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_auto_20210505_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
