# Generated by Django 3.1.7 on 2021-03-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210330_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribs',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userattribs',
            name='full_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userattribs',
            name='moblie_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='userattribs',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
