# Generated by Django 3.1.7 on 2021-03-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210330_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userattribs',
            old_name='moblie_number',
            new_name='mobile_number',
        ),
    ]
