# Generated by Django 3.1.6 on 2021-04-07 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210406_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applied_candidates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.userattribs'),
        ),
    ]
