# Generated by Django 3.1.7 on 2021-04-07 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_project_applied_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='applied_candidates',
        ),
        migrations.AddField(
            model_name='userattribs',
            name='applied_projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project'),
        ),
    ]
