# Generated by Django 3.1.7 on 2021-04-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210408_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribs',
            name='assigned_project',
            field=models.ManyToManyField(blank=True, to='backend.Project'),
        ),
    ]
