# Generated by Django 3.1.6 on 2021-04-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210408_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattribs',
            name='assigned_project',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Project'),
        ),
    ]
