# Generated by Django 3.1.7 on 2021-04-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20210409_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='published',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.userattribs'),
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
        migrations.AddField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
