# Generated by Django 3.1.6 on 2021-04-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_project_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tags',
            new_name='tags_requirement',
        ),
    ]
