# Generated by Django 3.1.7 on 2021-04-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20210412_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_question',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
