# Generated by Django 3.1.7 on 2021-04-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20210412_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_question',
            name='rel_project',
        ),
        migrations.AddField(
            model_name='project_question',
            name='project_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
