# Generated by Django 3.1.6 on 2021-04-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20210412_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_question',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes'),
        ),
    ]
