# Generated by Django 3.1.7 on 2021-04-15 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_project_question_answered_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_question',
            name='project_title',
        ),
        migrations.AddField(
            model_name='project_question',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project'),
        ),
    ]
