# Generated by Django 3.1.7 on 2021-04-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20210415_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_question',
            name='project_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
