# Generated by Django 3.2 on 2021-04-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribs',
            name='worth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
